WIP 130316S184210

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,10 +2,10 @@
 # -*- mode: shell-script -*-
 
 PROG=$(basename $0)
-BASEDIR=${BASEDIR:-"$(dirname $(realpath $0))"}
+REALPATH=${REALPATH:-realpath}
+BASEDIR=${BASEDIR:-"$(dirname $($REALPATH $0))"}
 SUPPORTDIR=${SUPPORTDIR:-"$(dirname $(dirname $BASEDIR))/support"}
 VENV=${VENV:-"$SUPPORTDIR/virtualenv"}
-source "$VENV/bin/activate"
 
 LOGFILE=${LOGFILE:-"$0.log"}
 PRODSITE=prod
@@ -119,6 +119,39 @@ function gitpull {
   return 0
 }
 
+function invenv {
+  local pyex="$VENV/bin/python"
+  if [[ -z $VENV || ! -x $pyex ]]; then
+     error "VENV ($VENV) does not point to a valid virtualenv directory"
+  fi
+
+  [[ $VIRTUAL_ENV == $VENV && $(which python) == $pyex ]] && \
+    python -c 'import sys; sys.real_prefix' 2>/dev/null
+}
+
+function maybe_activate_virtualenv {
+  if invenv; then return; fi
+
+  source "$VENV/bin/activate" || error "failed to activate virtualenv: $?"
+
+  if invenv; then return; fi
+
+  error 'failed to activate virtualenv (reason unknown)'
+}
+
+function runpip {
+  _debug -n "running pip install... "
+  # the next line should not be necessary, but, just in case...
+  maybe_activate_virtualenv
+  python -c 'import numpy; print numpy.__file__' 2>/dev/null || echo 'no numpy'
+  pip install -v numpy || \
+    error "pip install numpy failed: $?"
+  pip install -r $BASEDIR/requirements.txt || \
+    error "pip install -r $BASEDIR/requirements.txt failed: $?"
+  _debug 'done'
+  return 0
+}
+
 function builddb {
   if $FULL; then
     _debug -n 'building db... '
@@ -172,7 +205,7 @@ function deploy {
   echo $(date --iso-8601=seconds) \($(date +%A)\) >>"$LOGFILE"
   echo "deployed by $USER ($UID) connected from ${SSH_CLIENT/ *}" >>"$LOGFILE"
   echo >>"$LOGFILE"
-  gitpull && builddb && makeimg && moveimg && collectstatic && killfcgi
+  gitpull && runpip && builddb && makeimg && moveimg && collectstatic && killfcgi
   echo done
 }
 
